server {
	listen 80;
	root /var/www/html;
	index index.html;
	#server_name localhost;
	server_name creator-h5.yizhiweixin.com;

	location / {
		try_files $uri $uri/ /index.html;
      # 可以缓存，没变就用缓存，有变就重新下载
	  add_header Cache-control no-cache;
	}
   
	location ~ /\.ht {
		deny all;
	}
}